services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: golang:1.25-alpine
    container_name: migrator
    restart: "no"
    profiles: ["tools"]
    env_file:
      - postgres.env
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "go run github.com/pressly/goose/v3/cmd/goose@v3.24.1 -dir ./migrations postgres \"postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@postgres:5432/$${POSTGRES_DB}?sslmode=disable\" up"
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - app.env
    ports:
      - "50051:50051"
      - "8080:8080"
    command: ["./app"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # --- Observability ---
  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    volumes:
      - ./deploy/loki/loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.4.2
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./deploy/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./deploy/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - postgres
      - prometheus
      - loki
      - jaeger

volumes:
  postgres_data:
